import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/utils/navbar/Navbar";
import Footer from "@/utils/footer/Footer";
import { contextProvider } from "@/context/Context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Four",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <contextProvider>
          <Navbar />
          {children}
          <Footer />
        </contextProvider>
      </body>
    </html>
  );
}
